### ISSUE TITLE
List index out of range in gcode analysis

### ISSUE THREAD

**Issue by Billiam** [chatrat12/layerdisplay#1]
I received this error when loading a gcode file, sliced with slic3r 

```
2018-07-18 13:02:57,267 - octoprint.plugin - ERROR - Error while calling plugin layerdisplay
Traceback (most recent call last):
  File "/home/octoprint/src/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.9rc3-py2.7.egg/octoprint/plugin/__init__.py", line 225, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/octoprint/src/OctoPrint/venv/lib/python2.7/site-packages/layerdisplay/__init__.py", line 20, in on_event
    self.print_job = PrintJob(payload)
  File "/home/octoprint/src/OctoPrint/venv/lib/python2.7/site-packages/layerdisplay/PrintJob.py", line 17, in __init__
    self.layer_change_info = self._get_layer_info(file_selected_payload['file'])
  File "/home/octoprint/src/OctoPrint/venv/lib/python2.7/site-packages/layerdisplay/PrintJob.py", line 53, in _get_layer_info
    return GCodeAnalyzer.get_print_job_layer_information(gcode, fileSize)
  File "/home/octoprint/src/OctoPrint/venv/lib/python2.7/site-packages/layerdisplay/GCodeAnalyzer.py", line 22, in get_print_job_layer_information
    gCode = line_components[0]
IndexError: list index out of range
```

And the gcode: [20m_sphere.zip](https://github.com/chatrat12/layerdisplay/files/2206842/20m_sphere.zip)

**Comment by prgmatic** [comment]
Thank you for the gcode, fixing now!

**Comment by prgmatic** [comment]
Thank you for the report, the log, and the gcode :) Issue should be fixed. You can snag the fix through the 'Software Update' tab in OctoPrint settings.

Commit: https://github.com/chatrat12/layerdisplay/commit/bdb79cdba0ccf7cb8cfcb7af1847d8987dee2163
