### ISSUE TITLE
Plugin uses deprecated field `file` from FileSelected event payload that's going to be removed in 1.4.0

### ISSUE THREAD

**Issue by foosel** [chatrat12/layerdisplay#8]
```
2019-12-12 11:49:50,627 - octoprint.plugin - ERROR - Error while calling plugin layerdisplay
Traceback (most recent call last):
  File "C:\Devel\OctoPrint\OctoPrint\src\octoprint\plugin\__init__.py", line 224, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "C:\Devel\OctoPrint\devenv\lib\site-packages\layerdisplay\__init__.py", line 21, in on_event
    self.print_job = PrintJob(payload)
  File "C:\Devel\OctoPrint\devenv\lib\site-packages\layerdisplay\PrintJob.py", line 19, in __init__
    self.file_path = file_selected_payload['file']
KeyError: 'file'
```

Compare to [the docs](http://docs.octoprint.org/en/master/events/index.html#file-handling):

![image](https://user-images.githubusercontent.com/83657/70706541-5ef64b80-1cd6-11ea-9f17-cb6e0915989a.png)

See also https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/99 from another plugin, also contains steps to solve.

**Comment by aerickson** [comment]
I've got a working fix with installation directions in #11.
